### ISSUE TITLE
VAF calculation

### ISSUE THREAD

**Issue by byoo** [smalikic/B-SCITE#2]
https://github.com/smalikic/B-SCITE/blob/d62f451e0210b6117a27a0d8aa56cf84361ec508/src/Mutation.h#L20

Thank you for sharing B-SCITE. I have a questions about VAF calculation. I wonder why 2 is multiplied to numerator. Would you help me understand the VAF calculation?
Thank you.

**Comment by smalikic** [comment]
Wherever **VAF** is mentioned in the current version of the code, it refers to 2*var_reads/(var_reads + ref_reads) and should not be mistaken for **variant allele frequency** used in the literature and defined as var_reads/(var_reads + ref_reads).

**Comment by byoo** [comment]
Thanks a lot for your prompt advice! What does VAF stand for in this context?

**Comment by smalikic** [comment]
The meaning of the formula is: expected fraction of cells harbouring mutation. The term **VAF**  does indeed originate from "variant allele frequency" - we should consider **doubleVAF** or **ECF** in the future as alternatives to the currently used **VAF**. Thanks for pointing to this. Hope that these answer your question.

**Comment by byoo** [comment]
I see. It's like tumor purity. Thanks again for your kind explanation!
