### ISSUE TITLE
Bulk sequencing input file

### ISSUE THREAD

**Issue by byoo** [smalikic/B-SCITE#3]
https://github.com/smalikic/B-SCITE/blob/d62f451e0210b6117a27a0d8aa56cf84361ec508/src/Mutation.h#L21

I wonder what information is required in the INFO field. In the example file, I am not sure what the trueNode is, and trueVAF and ID seems redundant. Thank you!

**Comment by smalikic** [comment]
You can just provide "NA" string or anything else. This field does not have any particular use in the model and scoring.

**Comment by byoo** [comment]
Got it. Thanks again!
